name: flutter_matrix_html
description: A Flutter widget for rendering static html tags as Flutter widgets. (Will render over 70 different html tags!)
version: 0.11.1
author: Matthew Whitaker <sub6resources@gmail.com>
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.2'

dependencies:
  html: ^0.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

